# This line is not needed anymore - is obsolite
version: '3.8'

services:
  frontendser:
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: front

  backendser:
    build: ./example-backend
    ports:
      - 8080:8080
    container_name: back
